SELECT 'YOUNGEST' as Type, NAME, BIRTHDAY
FROM WORKER
WHERE BIRTHDAY = (SELECT MIN (BIRTHDAY)  FROM WORKER)  
UNION
SELECT 'OLDEST' as Type,  NAME, BIRTHDAY
FROM WORKER
WHERE BIRTHDAY=(SELECT MAX(BIRTHDAY)  FROM WORKER)  
ORDER BY  BIRTHDAY DESC;
