CREATE TABLE client (
    ID INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK
    (CHAR_LENGTH(NAME)>1 and CHAR_LENGTH(NAME)<1001)
);

CREATE TABLE worker (
    ID INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK
    (CHAR_LENGTH(NAME)>1 and CHAR_LENGTH(NAME)<1001),
    BIRTHDAY DATE CHECK(BIRTHDAY > '1900-01-01'),
    LEVEL VARCHAR(7) CHECK
    (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK
    (SALARY>100 and SALARY<100000)
);

CREATE TABLE  project(
    ID INT PRIMARY KEY,
    CLIENT_ID  INT,
    START_DATE  DATE,
	FINISH_DATE  DATE
);

CREATE TABLE PROJECT_WORKER  (
	PROJECT_ID INT,
	WORKER_ID INT,
	PRIMARY KEY (PROJECT_ID, WORKER_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
	FOREIGN KEY (WORKER_ID) REFERENCES WORKER(ID)
);
